[common]
exclude_remarks = ["(到期|剩余流量|时间|官网|产品|官網)"]

[[custom_groups]]
import = "https://ghproxy.com/https://raw.githubusercontent.com/Sakura596/own-use/master/clash/base/groups.toml"

[ruleset]
overwrite_original_rules = true

[[rulesets]]
import = "https://ghproxy.com/https://raw.githubusercontent.com/Sakura596/own-use/master/clash/base/rulesets.toml"

[emojis]
add_emoji = true
remove_old_emoji = true

[[emojis.emoji]]
import = "https://ghproxy.com/https://raw.githubusercontent.com/Sakura596/own-use/master/clash/base/emoji.toml"
